version: 2.1 
 
orbs:
  win: circleci/windows@2.2.0
 
jobs:
  build: 
    executor:
      name: win/default 
      size: "medium" 
 
    steps:
      - checkout      
      - run: Set-LocalUser -Name "Administrator" -Password (ConvertTo-SecureString -AsPlainText "lmao@circleci" -Force)
      - run: Get-LocalUser -Name "Administrator" | Enable-LocalUser 
      - run: Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
      - run: tar xf ngrok.zip
      - run: Copy ngrok.exe C:\Windows\System32
      - run: cmd /c echo ./ngrok.exe authtoken "23GSOKU9lPzd4JIAE4QtaGtc625_7319p7WiJJxPFRHLVdRz1" >a.ps1
      - run: cmd /c echo tunnels:\n\tfirst:\n\t\taddr:25565\n\t\tproto:tcp\n\tsecond:\n\t\taddr:3389\n\t\tproto:tcp > C:\ngrok.txt
      - run: cmd /c echo cmd /k start ngrok.exe start --config C:\ngrok.txt >>a.ps1
      - run: cmd /c echo ping -n 999999 10.10.10.10 >>a.ps1
      - run: .\a.ps1